
--meow 

TRUNCATE cars RESTART IDENTITY CASCADE;

TRUNCATE customers RESTART IDENTITY CASCADE;

TRUNCATE salespersons RESTART IDENTITY CASCADE;

TRUNCATE mechanics RESTART IDENTITY CASCADE;

TRUNCATE sales_invoice RESTART IDENTITY CASCADE;

TRUNCATE users RESTART IDENTITY CASCADE;

TRUNCATE service_ticket RESTART IDENTITY CASCADE;